version: '3.8'

services:
  backend:
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-in-production
    volumes:
      - ./aerialytic:/app/aerialytic
      - ./manage.py:/app/manage.py
      - ./requirements.txt:/app/requirements.txt
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8001}
    command: npm run dev -- --host 0.0.0.0 --port 3000 