apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  secret-key: cHJvZC1zZWNyZXQta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24tMTIzNDU=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: aerialytic-backend:latest
        ports:
        - containerPort: 8001
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /admin/
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /admin/
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        env:
          - name: DEBUG
            value: "False"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: secret-key
          - name: ALLOWED_HOSTS
            value: "backend-service,localhost,127.0.0.1"
          - name: DATABASE_URL
            value: "postgresql://aerialytic_user:aerialytic_password@postgres:5432/aerialytic"
          - name: CORS_ALLOWED_ORIGINS
            value: "http://frontend-service:80,http://localhost:3000"
          - name: DJANGO_SETTINGS_MODULE
            value: "aerialytic.settings"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer